### ISSUE TITLE
Multiple screens

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#10]
When working with the other PETSCII editor, I constantly use multiple screens for my drawings. They are perfect for comparing different versions, making "backups" on the fly, planning animations etc.

- Plus and Minus buttons to create more screens
- switch between screens
- delete screens
- per screen undo/redo (would be awesome)

**Comment by nurpax** [comment]
I did give this some thought earlier too. I dislike ”free movable windows” (could be just me, but I hate to organize windows by moving them). Maybe the multiple screens could work with the ”tab” paradigm? There’s a lot of empty space at the top and a tab selector would fit well there. Hovering on the tab selector could show a small preview of the tab contents. 

I think this is needed but I will need to do some refactoring first so that my redux state doesn’t get too messy. I guess each screen needs its own undo stack too?

**Comment by Esshahn** [comment]
![screenshot 2018-07-20 um 10 36 01](https://user-images.githubusercontent.com/434355/42992431-c99babd4-8c08-11e8-8957-23db17b28bd5.jpg)

It's done quite similar here, yes.
+1 from me if I could always see the thumbnail of the other screens

**Comment by nurpax** [comment]
Here's a quick'n'dirty test of multiscreen support with undo stack per screen:

https://www.youtube.com/watch?v=4Sv0N4pk4UQ

This was quite a bit trickier to do in redux than I thought. In fact, could be the hardest thing I've done in Redux so far. :)  Not checked-in yet as I need to clean it up.  Also the UI is definitely not final, the two screen select buttons are there just so that I could test the multiscreen-multiundo redux code.

**Comment by Esshahn** [comment]
Super cool. My number one to do request would be to include thumbnails for previewing the tabs. It's like 50% of the actual feature, as I constantly visually compare screens by looking at the thumbnails.

**Comment by Esshahn** [comment]
![bildschirmfoto 2018-07-22 um 10 27 13](https://user-images.githubusercontent.com/434355/43043735-d5c51caa-8d99-11e8-962b-01ac62597124.png)

Reason why I'm thinking to include it in Spritemate was a request to name sprites for better structure and information in the exported ASM source. With this layout name's could easily be displayed. Also sorting would be easy (drag 'n' drop jquery) and the controls for copy & trash would fit naturally.

But it's a lot of work and might be overkill for many.
I reverted all code related to this layout because I would sacrifice viewing all sprites next to each other.

**Comment by nurpax** [comment]
I originally thought that it’d work by hovering over the tab but the whole hover business is unnecessary as I can just show screen contents in the tab selector like in your mock up. (btw thanks for the mock, good way to communicate!)

I agree this is needed. This is next on my list (this and fixing save/load).

**Comment by Esshahn** [comment]
You are my hero.

**Comment by nurpax** [comment]
My initial design for doing this didn't pan out performance-wise.

The screen contents are rendered as a 40x25 grid of <img>s.  So I thought I'll just render the previews using the same code for char grid rendering but with a <div> around it that scales the contents smaller.

This works (see video and/or https://github.com/nurpax/petski/tree/multiscreen-preview) but unfortunately it totally destroys performance with multiple screens.

I didn't profile this yet but there's very little React code happening in rendering the previews (since they don't change).  So no re-rendering.  I suspect it could be that Chrome can't keep up with all the images.  Or it could be the :hovers that I use in the character grid renderer (this should be disabled in preview anyway).

Best approach probably would be to periodically turn current framebuffer contents into a single image and then render the tab previews with just a single image.

**Comment by Esshahn** [comment]
I see. Not that it is a related issue, but I had the same kind of performance slowdowns when I introduced the window that shows all sprites. Turned out that I did a redraw of every single canvas whenever the editor view was updated, quickly bringing drawing to a halt after 100+ canvasses to update.

I solved it by having two update methods: update_one_canvas and update_all_canvas

I'm not sure about react and how it treats the DOM, but it seems like it just becomes too many elements to update with every refresh?

**Comment by Esshahn** [comment]
(just offering a ping-pong here, it's unlikely I find the problem, but making me explain will likely help you figure out the solution...)

**Comment by nurpax** [comment]
React performs a virtual dom diff and updates only what changed.  But in my case, I get bad performance even when React does nothing (ie., the window has been rendered first with React and then further frames are just the browser responding to CSS :hovers).

I did take a look at Chrome dev tools performance tab and it shows something called "Update Layer Tree" at the top -- AFAIK this is Chrome doing .  Will need to read a bit more about how to profile this.

If I'm lucky, it could be related to https://github.com/nurpax/petski/issues/26.

**Comment by nurpax** [comment]
But anyway.. 10 tabs with 1000 `<img>`s in each is 10K DOM nodes.  It's not completely surprising that this would cause some perf problems. :)

**Comment by Esshahn** [comment]
yeah I figured. That's the beauty of the canvas object...

**Comment by nurpax** [comment]
Might have to switch to that.

I'll clean up multiscreen stuff otherwise first (undo add/remove screen, save/load, etc.), get back to this then.

**Comment by nurpax** [comment]
Canvas is.. so fast!  

Checked in tab contents preview here: https://github.com/nurpax/petski/commit/c75c133595105cfe3c931bcdaf489a87fc15f6af

**Comment by nurpax** [comment]
Further work in https://github.com/nurpax/petmate/issues/30, https://github.com/nurpax/petmate/issues/29, https://github.com/nurpax/petmate/issues/28
