### ISSUE TITLE
Export as image

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#19]
- GIF
- PNG

Extra bonus if all screens (if you go multi-screen) could be combined as an animated GIF

**Comment by nurpax** [comment]
I'll add PNG/GIF for first release because I'd like people to be able to easily share any art they may have made in this editor.  Without this export, they'd need to screencap the editor.

Animation can be done later.. it will probably require the multiscreen tabs to be draggable, removable, etc first.

**Comment by nurpax** [comment]
png export works now
