### ISSUE TITLE
Keyboard shortcuts for the tools

### ISSUE THREAD

**Issue by Viza74** [nurpax/petmate#54]
what the title says. :)

Primarily for the draw and colorize tools.

**Comment by nurpax** [comment]
Marking this with "keyboard" label.  There are many keyboard shortcut related issues.

I added a wiki for designing keyboard shortcuts: https://github.com/nurpax/petmate/wiki/Keyboard-shortcut-design

Should try to design all the shortcuts comprehensively so that they feel consistent.  If we add them one by one, it might get messy and inconsistent.

**Comment by Viza74** [comment]
Ohh, one more thing: the current "brush" tool functionality could be very naturally moved to right mouse too, because it is actualy some kind of "pick up". Like "shift + right mouse drag" selects brush, and automatically swiches to brush mode. And as I mentioned in some other issue, I would like to see a "move" version of the brush tool, which clears the area of the original selection, that could be "cmd+right mouse drag"

**Comment by nurpax** [comment]
I was going to suggest:

- 'b' - brush (select brush, draw with brush) (I don't understand why this would renaming the brush tool)
- 'c' - colorize
- 'x' - for draw (because 'd' is taken.. but hey, 'x' marks the spot, e.g. draw :))

Agreed that clear canvas doesn't need a shortcut.  In fact I will most likely replace it with "clear rect" to fill a rectangle.

```
Suggestions:
wasd - move in character palette
qe - move in color palette
```
For the record, the above are the way it works in Git HEAD (IIRC in 0.2.0 too for wasd).

**Comment by Esshahn** [comment]
> Agreed that clear canvas doesn't need a shortcut. 
But it deserves an entry in the menu

**Comment by Viza74** [comment]
> (I don't understand why this would renaming the brush tool)
Because IMO what is called "draw" in petmate is called "brush" in every other drawing program. At least the functionality maps best for "brush" in other programs. 
What is called "brush" in petmate is "clone", or "copy-paste" in other programs IMO. Maybe when there will be a brush palette to store and choose multiple brushes from the canvas it will deserve the "brush"  name, but right now it is closer to copy-paste.
But there is definitely a gray area here in overlapping functionality, so it doesn't really matter...

>> Agreed that clear canvas doesn't need a shortcut.
> But it deserves an entry in the menu

You two seems to be strangely attached to that clear canvas tool... :) I don't really understand why, though.
IMO thats a very rarely used option (maybe usefull during program testing, but in real world use?)
I can't recall any drawing program that's show an instant "clear canvas" functionality this prominently.
But anyway, I don't want to take away your favorite tool :) I do not mind if thats sit there, I just think it is way less important than top spot in the toolbar...

**Comment by Esshahn** [comment]
Not toolbar. The menu.

**Comment by Viza74** [comment]
Ohh, ok, I misunderstood.
The menu could be ok.
In the "edit" menu.
But IMO the right click menu of the screen thumbnails would be the most natural place to put the clear canvas function (as it is a screen-wide function). But the edit menu is also retty good

(Somewhat off-topic here, but the thumbnail right-click menu is a bit too hidden - i think the best would be a small drop-down arrow on thumbnail hover to access that menu.)

**Comment by nurpax** [comment]
I guess it never occurred to me that 'brush' might not be the best name for that feature.  We can try to come up with a better name for it.

However, I have several good changes lined up for the next release, so I'll go ahead and implement shortcuts as in my above reply.  We can change them then once this discussion concludes.  It's better we have the shortcuts in there -- other use patterns depend on them.

**Comment by nurpax** [comment]
I added two sets for tool selection:

- 'x', 'c', 'b'
- '1', '2', '3'

Both do the same.  Give it a try and see which feels better.  I'll make a build in the next 10 mins.

Unfortunately I still couldn't get right click to work reliably on Electron.  I can attach an event handler for "context menu" and get the events.. but a right click also issues a left-click (!), at least on my Mac where I need to press ctrl-left-click to pop the context menu.  Not sure if this would work with a real mouse and/or on Windows.

Would it be a totally bad idea to use say COMMAND-leftclick instead of right click?

**Comment by nurpax** [comment]
0.2.3 contains the shortcuts.  Up in the usual location.

**Comment by Viza74** [comment]
I suggested alt+left click, because thats the color picker in Photoshop.

**Comment by nurpax** [comment]
So alt-left to pick char and color under cursor?  

Also add a picker icon in the left menu bar, selectable with a shortcut ('i' and maybe '4' if I'm reading right from above)?

The icon probably wouldn't be used much as alt-left would be quicker, but I'd like these features to be somehow visible in the UI.  Easier to get started this way rather than rely only on invisible keyboard shortcuts.

**Comment by Viza74** [comment]
Yes.

In other news: I tried 0.2.3 and happy to report that the hotkeys made the program approximately 1.493 bazillion times more useable. :)

Also, I just realized that I can "abuse" the brush tool to simulate "pick" behaviour (with the somewhat strange shortcut -> "Esc" to pick) which added another 0.793 bazillion to the useablity multiplier. :)

**Comment by nurpax** [comment]
Alt-left-click is in 0.2.4.  This should be another c*bazillion productivity improvement :)

**Comment by Viza74** [comment]
Yepp, helps a lot too.

One small issue: if in brush mode, and alt-click pick a character, the app should switch back to draw mode (as it does when selecting from the character palette in brush mode).
Also it should switch to draw mode from colorize mode too if selecting something from the character palette. But not on alt-pick.

**Comment by nurpax** [comment]
Implemented @Viza74 's last suggestion too
